trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python310:
      python.version: '3.10'
    Chromium:
      browser: 'chromium'
    Firefox:
      browser: 'firefox'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true

- script: |
    pip install robotframework
    pip install robotframework-browser
    pip install webdrivermanager
    webdrivermanager firefox chrome --linkpath /usr/local/bin
  displayName: Install dependencies

- script: robot -d ./logs -i get_an_activity .
  displayName: Run Web Test
