trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Chromium:
      browser: 'chromium'
    Firefox:
      browser: 'firefox'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r web_requirements.txt
    pip install rfbrowser init
  displayName: Install dependencies

- script: robot -d ./logs_web -v BROWSER:$(browser) -e servicetest -e mobiletest .
  displayName: Run Web Test
