trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

strategy:
  maxParallel: 2
  matrix:
    Chromium:
      browser: 'chromium'
    Firefox:
      browser: 'firefox'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r web_requirements.txt
    rfbrowser init
  displayName: Install dependencies

- script: robot -d ./logs_web -x output-xunit.xml -v BROWSER:$(browser) --listener RetryFailed -e servicetest -e mobiletest .
  displayName: Run Web Test
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'logs_web/output-xunit.xml'
  displayName: 'Publish Test Results'
