# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

stages:
  - stage: Install Python 3.8
  strategy:
    Python38:
      python.version: '3.8'

jobs:
  - job: Windows
  pool:
    vmImage: windows-latest
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r web_requirements.txt
    rfbrowser init
  displayName: 'Install dependencies'

- bash: |
    robot -d ./logs_web -x output-xunit.xml --listener RetryFailed -e servicetest -e mobiletest .
  continueOnError: true
  displayName: 'Run Web Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'logs_web/output-xunit.xml'
  displayName: 'Publish Test Results'