trigger:
- main

pr:
- none

jobs:
- job: MeuJob
  strategy:
    matrix:
      browser: [ 'chromium' ]
  steps:
  - script: Executando o job com o browser $browser
  
  - job: ConfigurarAmbiente
    displayName: "Configurar ambiente"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Configurando ambiente no Ubuntu"
    
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: "Instalar e usar o Python"
      
    - script: pip install -r requirements.txt
      displayName: "Instalar dependências do requirements.txt"
      
  - job: ExecutarTestesWeb
    displayName: "Executar testes web"
    dependsOn: ConfigurarAmbiente
    steps:
    - script: echo "Executando testes web com o browser $browser"
    
    - script: |
        robot -d TestResults --variable BROWSER:$browser Tests
      displayName: "Executar testes Robot Framework"