trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Chromium:
      browser: 'chromium'
    Firefox:
      browser: 'firefox'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    pip install robotframework
    pip install robotframework-browser
    pip install webdrivermanager
    webdrivermanager firefox chrome --linkpath /usr/local/bin
  displayName: Install dependencies

- script: robot -d ./logs_web -v BROWSER:$(browser) -e servicetest -e mobiletest .
  displayName: Run Web Test
