trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      python.version: '3.8'
      browser: 'chromium'
    Python39:
      python.version: '3.9'
      browser: 'firefox'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true

- script: |
    pip install robotframework
    pip install robotframework-browser
    pip install webdrivermanager
    webdrivermanager firefox chrome --linkpath /usr/local/bin

- script: |
    robot --variable BROWSER:${{ matrix.browser }} tests/
  displayName: 'Run tests'
