image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Install dependencies
        script:
          - apt-get update
          - apt-get install -y curl python3 python3-pip
          - curl -sL https://deb.nodesource.com/setup_14.x | bash -
          - apt-get install -y nodejs
          - pip3 install robotframework-browser
          - npx playwright install
          - rfbrowser init

pr:
  branches:
    includes:
      - main
      - develop
      - feature/*
