image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Install dependencies
        script:
          - apt-get update
          - apt-get install -y curl python3 python3-pip
          - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\
          - apt-get install -y nodejs
          - export PATH="$PATH:/usr/bin/npm:/usr/bin/npx"
          - npm install -g npx
          - pip3 install robotframework-browser
          - npx playwright install
          - rfbrowser init
          - cd /usr/local/bin/
          - ls

pr:
  branches:
    includes:
      - main
      - develop
      - feature/*
