[tool.robotidy]
diff = true
spacecount = 2
continuation-indent = 2
line-length = 150
transform = [
	"AddMissingEnd",
	"AlignKeywordsSection",
	"AlignSettingsSection",
	"AlignTestCasesSection",
    "AlignVariablesSection",
	"DiscardEmptySections",
	"IndentNestedKeywords",
	"MergeAndOrderSections",
	"NormalizeNewLines",
	"NormalizeSeparators",
	"NormalizeSettingName",
	"OrderSettings",
	"OrderSettingsSection"
]

[tool.robocop]
exclude = ["W0202"]
configure = [
 "line-too-long:line_length:150"
]
language = [
 "pt"
]