[tool.robotidy]
diff = true
spacecount = 3
continuation-indent = 4
line-length = 130
transform = [
	"AddMissingEnd",
	"AlignSettingsSection",
	"DiscardEmptySections",
	"IndentNestedKeywords",
	"OrderSettings",
	"OrderSettingsSection"
]

[tool.robocop]
configure = [
 "line-too-long:line_length:130"
]
language = [
 "pt"
]
