name: Android Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Appium
        run: |
          sudo apt-get update
          sudo apt-get install -y appium

      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-appium

      - name: Run tests
        run: |
          robot -l junit --output results.xml tests/

    after_success:
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: results
          path: results.xml
