name: Run Mobile Tests

run-name: On Push - Mobile Tests Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configuração do ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Instalação de dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r mobile_requirements.txt

      - name: Execução dos testes mobile
        run: |
          robot -d ./logs_mobile -e servicetest -e webtest

      - name: Download Tests Results
        if: always()
        uses: actions/download-artifact@v1
        with:
          name: results-android

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: results-android
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: false
