name: Teste Mobile Android

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker
      - name: Build Docker image
        run: |
          docker build -t test-mobile-android .
      - name: Run tests
        run: |
          docker run -it --rm test-mobile-android

  report:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download test results
        run: |
          wget -O results.xml localhost:4723/wd/hub/session/1/element/1/screenshot
      - name: Upload test results to S3
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
